# Generated by Django 4.2.16 on 2024-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_computing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Common', 'Common'), ('PMA Admin', 'PMA Admin'), ('Anonymous', 'Anonymous')], default='Common', max_length=20),
        ),
    ]
