# Generated by Django 4.2.16 on 2024-11-17 14:43

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_bio_alter_profile_computing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, default='profiles/images/testpfp.png', upload_to=profiles.models.upload_to_profile_folder),
        ),
    ]
