# Generated by Django 4.2.16 on 2024-11-17 14:48

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='profiles/images/testpfp.png', upload_to=profiles.models.upload_to_profile_folder),
        ),
    ]
