# Generated by Django 4.2.16 on 2024-11-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='computing_id',
            field=models.TextField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
