# Generated by Django 4.2.16 on 2024-10-19 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_in_s3', models.CharField(blank=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('class_belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pma_admins', models.ManyToManyField(blank=True, related_name='project_pma_admins', to=settings.AUTH_USER_MODEL)),
                ('users_with_access', models.ManyToManyField(related_name='project_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
