# Generated by Django 4.2.16 on 2024-10-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users_with_access',
            new_name='members',
        ),
    ]
