# Generated by Django 4.2.16 on 2024-10-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_users_with_access_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='class_belongs_to',
        ),
    ]
