# Generated by Django 4.2.16 on 2024-11-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_member_list'),
        ('projects', '0004_project_description_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='class_belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
