# Generated by Django 4.2.16 on 2024-11-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_joinrequest'),
        ('projects', '0005_project_class_belongs_to'),
    ]

    operations = [
    ]
