# Generated by Django 4.2.16 on 2024-11-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectcomment'),
        ('projects', '0006_merge_0004_joinrequest_0005_project_class_belongs_to'),
    ]

    operations = [
    ]
