# Generated by Django 4.2.16 on 2024-11-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20241103_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pma_admins',
        ),
    ]
