# Generated by Django 4.2.16 on 2024-11-01 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='member_list',
            field=models.ManyToManyField(blank=True, related_name='class_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
