# Generated by Django 4.2.16 on 2024-11-16 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_class_member_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='member_list',
            field=models.ManyToManyField(blank=True, related_name='classes_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
