# Generated by Django 4.2.16 on 2024-11-20 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_alter_class_member_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='pma_admins',
            field=models.ManyToManyField(blank=True, related_name='project_pma_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
