# Generated by Django 4.2.16 on 2024-10-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='owner',
        ),
    ]
