# Generated by Django 4.2.16 on 2024-10-19 23:46

from django.db import migrations, models
import django.db.models.deletion
import doc.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('doc', '0002_rename_user_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=doc.models.upload_to_project_folder),
        ),
    ]
