# Generated by Django 4.2.16 on 2024-11-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_document_project_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='class_name',
        ),
    ]
