# Generated by Django 4.2.16 on 2024-10-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_documentcomment_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='creation_date',
            field=models.DateField(blank=True, help_text='Optional: When was this document created?', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Describe the contents of this file'),
        ),
        migrations.AddField(
            model_name='document',
            name='due_date',
            field=models.DateField(blank=True, help_text='Optional: Is there a due date for this document?', null=True),
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='doc.tag'),
        ),
    ]
