# Generated by Django 4.2.16 on 2024-10-28 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_tag_document_creation_date_document_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='creation_date',
        ),
    ]
