# Generated by Django 4.2.16 on 2024-10-28 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0006_remove_document_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_documents_set', through='doc.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_set', to='doc.document'),
        ),
    ]
