# Generated by Django 4.2.16 on 2024-10-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_document_liked_by_alter_like_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_users', to='doc.document'),
        ),
    ]
