# Generated by Django 4.2.16 on 2024-11-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_remove_document_class_name'),
        ('doc', '0008_alter_like_document'),
    ]

    operations = [
    ]
